development:
  adapter: postgresql
  encoding: unicode
  database: redirect
  pool: 5
  # username: MinKim
  # password:
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: redirect
  pool: 5
  # username: MinKim
  # password:
  host: localhost
